# Credentials are read from environment variables 

footballflow:
  target: dev
  outputs:

    dev:
      type: snowflake
      account:   "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user:      "{{ env_var('SNOWFLAKE_USER') }}"
      password:  "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role:      "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database:  "{{ env_var('SNOWFLAKE_DATABASE', 'FOOTBALLFLOW') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      schema:    STAGING
      threads:   4
      client_session_keep_alive: false
      query_tag: dbt_footballflow_dev

    prod:
      type: snowflake
      account:   "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user:      "{{ env_var('SNOWFLAKE_USER') }}"
      password:  "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role:      "{{ env_var('SNOWFLAKE_ROLE', 'ACCOUNTADMIN') }}"
      database:  "{{ env_var('SNOWFLAKE_DATABASE', 'FOOTBALLFLOW') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      schema:    STAGING
      threads:   8
      client_session_keep_alive: false
      query_tag: dbt_footballflow_prod
